apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-disk-migration-main-rpc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
  storageClassName: azurefile-premium
  volumeMode: Filesystem